name: aplicacion_conductores
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"  # Ajustado para Flutter

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2      # Actualizado
  http: ^1.3.0
  workmanager: ^0.5.0
  permission_handler: ^11.3.1  # Actualizado
  firebase_core: ^3.11.0   # Actualizado
  firebase_auth: ^5.4.2    # Actualizado
  firebase_auth_web: ^5.0.0
  firebase_messaging: ^15.2.2  # Actualizado
  cloud_firestore: ^5.6.3  # Actualizado
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.1.14 # Asegúrate de tener la última versión
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  assets:
    - assets/images/
    
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"  # Ruta correcta si la imagen está en la carpeta assets/images/
  remove_alpha_ios: true  # Esto eliminará el canal alfa para iOS
